version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: "./node.dockerfile"
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: "yarn start"
    depends_on:
      - db
    networks:
      - network-develop
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    networks:
      - network-develop

networks:
  network-develop:
    driver: bridge
